mutation DeleteMedia($id: ID!) {
  deleteMedia(id: $id) {
    id
    title
    description
    category
    mediaType
    videoPlayerInfo {
      currentTime
      duration
    }
    file {
      name
      mimetype
      encoding
      size
      url
    }
    createdAt
    updatedAt
    deletedAt
  }
}
