# Use root/example as user/password credentials
version: '3.1'

volumes:
  redis_cache:

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    environment:
      REDIS_PWD: 'my-redis'
    ports:
      - '6078:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_PWD
    volumes:
      - redis_cache:/data
    
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/
