query Change($refreshToken: String!) {
  changePassword(refreshToken: $refreshToken) {
    id
    firstName
    lastName
    fullName
    email
    role
    username
    isVerified
    progress
    phone
    country
    avatarUrl
    program
    platform
    refreshToken {
      expiresAt
      token
    }
    refreshToken {
      expiresAt
      token
    }
    isAuthenticated
    createdAt
  }
}