query Forget($email: String!) {
  forgetPassword(email: $email) {
    id
    firstName
    lastName
    fullName
    email
    role
    username
    isVerified
    progress
    phone
    country
    avatarUrl
    program
    platform
    email {
      expiresAt
      token
    }
    email {
      expiresAt
      token
    }
    isAuthenticated
    createdAt
  }
}