mutation SignIn($input: AuthUser!) {
  signIn(input: $input) {
    id
    firstName
    lastName
    fullName
    email
    role
    username
    isVerified
    progress
    phone
    country
    avatarUrl
    program
    platform
    accessToken {
      expiresAt
      token
    }
    refreshToken {
      expiresAt
      token
    }
    isAuthenticated
    createdAt
  }
}
