query Users {
  usersCollection(last: 1) {
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    edges {
      cursor
      node {
        id
        fullName
        email
        firstName
        lastName
        avatarUrl
        phone
        country
        city
        enrollments {
          program
          platform
        }
      }
    }
  }
}
