query Users {
  users {
    id
    fullName
    email
    role
    username
    phone
    country
    avatarUrl
    isVerified
    progress
    program
    platform
    tokenExpiredAt
    loggedIn
    createdAt
  }
}
