mutation Auth($refreshToken: String!) {
  auth(refreshToken: $refreshToken) {
    id
    firstName
    lastName
    fullName
    email
    role
    username
    isVerified
    progress
    phone
    country
    avatarUrl
    program
    platform
    accessToken {
      expiresAt
      token
    }
    isAuthenticated
    createdAt
  }
}
