query Course($id: ID!) @cache(policy: CacheAndNetwork) {
  node(nodeId: $id) {
    nodeId
    ... on courses {
      id
      userId
      title
      code
      shortDescription
      description
      year
      startDate
      endDate
      dueDate
      thumbnailUrl
      coverUrl
      courseType
      tags
      status
      instructors
      studentIds
      createdAt
      updatedAt
    }
  }
}
