query GetMediaByType($type: MediaType!) {
  mediaByType(type: $type) {
    id
    title
    description
    category
    mediaType
    videoPlayerInfo {
      currentTime
      duration
    }
    file {
      name
      mimetype
      encoding
      size
      url
    }
    createdAt
    updatedAt
    deletedAt
  }
}
