type Forum {
  id: ID!
  name: String!
  description: String
  courseId: ID!
  postIds: [ID!]!
  tagIds: [ID!]!
  createdAt: Time
  updatedAt: Time
  deletedAt: Time
}

type ForumPost {
  id: ID!
  title: String!
  content: String!
  courseID: ID!
  author: ID!
  commentIds: [ID!]!
  fileIds: [ID!]!
  forumId: ID!
  userId: ID!
  tags: [ID!]!
  upvotes: Int!
  downvotes: Int!
  createdAt: Time
  updatedAt: Time
  deletedAt: Time
}

type ForumComment {
  id: ID!
  content: String!
  courseId: ID!
  userId: ID!
  postId: ID!
  parentId: ID!
  fileIds: [ID!]!
  upvotes: Int!
  downvotes: Int!
  createdAt: Time
  updatedAt: Time
  deletedAt: Time
}

type Tag {
  id: ID!
  name: String!
  postIds: [ID!]!
  courseIds: [ID!]!
}

input CreateForumInput {
  name: String!
  description: String
  courseId: ID!
  tags: [ID!]
}

input UpdateForumInput {
  name: String
  description: String
  tags: [ID!]
}

input CreateForumPostInput {
  title: String!
  content: String!
  courseId: ID!
  forumId: ID!
  userId: ID!
  tags: [ID!]
  files: [ID!]
}

input UpdateForumPostInput {
  title: String
  content: String
  tags: [ID!]
  files: [ID!]
}

input CreateForumCommentInput {
  userId: ID!
  parentId: ID!
  content: String!
  courseId: ID!
  postId: ID!
  files: [ID!]
}

input UpdateForumCommentInput {
  content: String
  files: [ID!]
}

input CreateTagInput {
  name: String!
}

input UpdateTagInput {
  name: String
}

extend type Query {
  forums(courseId: ID): [Forum!]!
  forum(id: ID!): Forum
  forumPosts(courseId: ID, tags: [ID!]!): [ForumPost!]!
  forumPost(id: ID!): ForumPost
  forumComments(courseId: ID): [ForumComment!]!
  forumComment(id: ID!): ForumComment
}

extend type Mutation {
  createForum(input: CreateForumInput!): Forum!
  updateForum(id: ID!, input: UpdateForumInput!): Forum!
  deleteForum(id: ID!): Forum!

  createForumPost(input: CreateForumPostInput!): ForumPost!
  updateForumPost(id: ID!, input: UpdateForumPostInput!): ForumPost!
  deleteForumPost(id: ID!): ForumPost!

  createForumComment(input: CreateForumCommentInput!): ForumComment!
  updateForumComment(id: ID!, input: UpdateForumCommentInput!): ForumComment!
  deleteForumComment(id: ID!): ForumComment!

  createTag(input: CreateTagInput!): Tag!
  updateTag(id: ID!, input: UpdateTagInput!): Tag!
  deleteTag(id: ID!): Tag!
}
