type Mail {
  id: ID!
  to: [String!]
  subject: String!
  body: String!
  attachmentUrl: String!
  status: String!
}

input MailInput {
  id: ID!
  to: [String!]!
  subject: String!
  content: Any
  attachmentUrl: String
  template: String!
}

extend type Mutation {
  sendMail(input: MailInput): Mail
  deleteMail(id: ID!): Mail
}

extend type Query {
  mail(id: ID!): Mail
  mails: [Mail]
}
