query GetTargetsByCourseId($courseId: ID!) {
  targets(courseId: $courseId) {
    id
    name
    description
    dueDate
    startDate
    courseId
    completionDate
    isCompleted
    targetType
    targetValue
    currentValue
    targetMetric
    reminders {
      id
      message
      sendTime
      sent
    }
    units
    repeatInterval
    repeatEndDate
    createdAt
    updatedAt
  }
}
