query User($id: String!) {
  usersCollection(filter: { id: { eq: $id } }) {
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    edges {
      cursor
      node {
        id
      }
    }
  }
}
