mutation CreateNotification($input: CreateNotificationInput!) {
  createNotification(input: $input) {
    id
    senderId
    recipientId
    courseId
    seen
    text
    title
    type
    link
    createdAt
    updatedAt
    deletedAt
  }
}
