mutation UpdateActivity($input: UpdateActivityInput!) {
  updateActivity(input: $input) {
    id
    userID
    courseID
    courseContentID
    activityType
    createdAt
    updatedAt
    deletedAt
  }
}
